rm -fr ./CODE-SPT-Code-TreeSitter/SPT-Code/sources/data/asts/vendor/tree-sitter-php/.git
rm -fr ./CODE-SPT-Code-TreeSitter/SPT-Code/sources/data/asts/vendor/tree-sitter-c-sharp/.git
rm -fr ./CODE-SPT-Code-TreeSitter/SPT-Code/sources/data/asts/vendor/tree-sitter-ruby/.git
rm -fr ./CODE-SPT-Code-TreeSitter/SPT-Code/sources/data/asts/vendor/tree-sitter-python/.git
rm -fr ./CODE-SPT-Code-TreeSitter/SPT-Code/sources/data/asts/vendor/tree-sitter-javascript/.git
rm -fr ./CODE-SPT-Code-TreeSitter/SPT-Code/sources/data/asts/vendor/tree-sitter-java/.git
rm -fr ./CODE-SPT-Code-TreeSitter/SPT-Code/sources/data/asts/vendor/tree-sitter-go/.git
rm -fr ./CODE-SPT-Code-TreeSitterV2/SPT-Code/sources/data/asts/vendor/tree-sitter-php/.git
rm -fr ./CODE-SPT-Code-TreeSitterV2/SPT-Code/sources/data/asts/vendor/tree-sitter-c-sharp/.git
rm -fr ./CODE-SPT-Code-TreeSitterV2/SPT-Code/sources/data/asts/vendor/tree-sitter-ruby/.git
rm -fr ./CODE-SPT-Code-TreeSitterV2/SPT-Code/sources/data/asts/vendor/tree-sitter-python/.git
rm -fr ./CODE-SPT-Code-TreeSitterV2/SPT-Code/sources/data/asts/vendor/tree-sitter-javascript/.git
rm -fr ./CODE-SPT-Code-TreeSitterV2/SPT-Code/sources/data/asts/vendor/tree-sitter-java/.git
rm -fr ./CODE-SPT-Code-TreeSitterV2/SPT-Code/sources/data/asts/vendor/tree-sitter-go/.git
rm -fr ./home/user1-selab3/Documents/research-shradha/deploy-spt-code/spt-code/sources/data/asts/vendor/tree-sitter-java/.git
rm -fr ./CODE-SPT-Code/spt-code/sources/data/asts/vendor/tree-sitter-php/.git
rm -fr ./CODE-SPT-Code/spt-code/sources/data/asts/vendor/tree-sitter-c-sharp/.git
rm -fr ./CODE-SPT-Code/spt-code/sources/data/asts/vendor/tree-sitter-ruby/.git
rm -fr ./CODE-SPT-Code/spt-code/sources/data/asts/vendor/tree-sitter-python/.git
rm -fr ./CODE-SPT-Code/spt-code/sources/data/asts/vendor/tree-sitter-javascript/.git
rm -fr ./CODE-SPT-Code/spt-code/sources/data/asts/vendor/tree-sitter-java/.git
rm -fr ./CODE-SPT-Code/spt-code/sources/data/asts/vendor/tree-sitter-go/.git
