apiVersion: batch/v1
kind: Job
metadata:
  name: {{ job_name }}
spec:
  ttlSecondsAfterFinished: 86400 # a day
  template:
    spec:
      automountServiceAccountToken: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - us-central 
      containers:
        - name: job-casual-model-train-container
          image: gitlab-registry.nrp-nautilus.io/gp-engine/jupyter-stacks/bigdata-2023:latest
          workingDir: /data
          command: ["sh", "-c", "bash run_install.sh && python3 /data/causal-model-a.py"]
          volumeMounts:
            - name: {{ pvc_name }}
              mountPath: /data
          resources:
            limits:
              memory: 21Gi
              cpu: "8"
              nvidia.com/gpu: 1
            requests:
              memory: 20Gi
              cpu: "8"    
              nvidia.com/gpu: 1
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: {{runAsUserID}}
      volumes:
        - name: {{ pvc_name }}
          persistentVolumeClaim:
            claimName: {{ pvc_name }}
      restartPolicy: Never
  backoffLimit: 1
