apiVersion: batch/v1
kind: Job
metadata:
  name: job08-train-mlm-model-gp-engine-unoselab01
spec:
  ttlSecondsAfterFinished: 86400 # a day
  template:
    spec:
      containers:
        - name: job-mlm-model-train-container
          image: gitlab-registry.nrp-nautilus.io/gp-engine/jupyter-stacks/bigdata-2023:latest
          workingDir: /data
          # command: ["sh", "-c", "bash run_install.sh && python3 train_mlm.py -train 1000 -test 100 -ngpu 2 -logfile logfile-jun14_gpu2.log"]
          # command: ["sh", "-c", "bash run_install.sh && python py_ver.py"]
          command: ["/bin/bash","-c"]
          args: ["cd /data;
                pip install scikit-learn==1.3.1;
                pip install transformers==4.34.0;
                pip install datasets==2.14.5;
                pip install sentencepiece==0.1.99;
                pip install sacremoses==0.0.53;
                pip install accelerate==0.23.0;
                pip install torch==2.1.0; 
                pip install torchvision==0.16.0; 
                pip install torchaudio==2.1.0;
                pip install prettytable==3.5.0;
                pip install psutil gputil;
                python train_mlm.py -train 1000 -test 100 -ngpu 4 -epoch 30 -logfile logfile-jun14_gpu4.log"]
          volumeMounts:
            - name: pvc-gp-engine-unoselab01
              mountPath: /data
          resources:
            limits:
              memory: 49Gi
              cpu: "4"
              nvidia.com/gpu: 4
              ephemeral-storage: 48Gi
            requests:
              memory: 49Gi
              cpu: "4"
              nvidia.com/gpu: 4
              ephemeral-storage: 48Gi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
      volumes:
        - name: pvc-gp-engine-unoselab01
          persistentVolumeClaim:
            claimName: pvc-gp-engine-unoselab01
      restartPolicy: Never
  backoffLimit: 1
