ARG CUDA=11.7
FROM nvidia/cuda:${CUDA}.1-cudnn8-devel-ubuntu20.04 AS build
ARG CUDA

# Use bash to support string substitution.
SHELL ["/bin/bash", "-c"]

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      build-essential \
      cmake \
      cuda-command-line-tools-${CUDA/./-} \
      git \
      tzdata \
      wget \
    && rm -rf /var/lib/apt/lists/*

# Install Miniconda package manager.
RUN wget -q -P /tmp https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda \
    && rm /tmp/Miniconda3-latest-Linux-x86_64.sh
ENV PATH="/opt/conda/bin:$PATH"

RUN conda install conda-forge::mamba && \
    mamba create -y -n mlm_env -c pytorch -c nvidia -c defaults -c conda-forge \
    python=3.11.3 pip tqdm pandas numpy \
    && conda activate mlm_env \
    && pip install \
        scikit-learn==1.3.1 \
        transformers==4.34.0 \
        datasets==2.14.5 \
        sentencepiece==0.1.99 \
        sacremoses==0.0.53 \
        accelerate==0.23.0 \
        torch==2.1.0 \
        torchvision==0.16.0 \
        torchaudio==2.1.0 \
        prettytable==3.5.0 \
    && conda clean -ya
