apiVersion: v1
kind: Pod
metadata:
  name: gp-engine-unoselab01-pod1
spec:
  containers:
  - name: causal-model-gp-engine-unoselab01-pod1
    image: ubuntu:20.04
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
    resources:
      limits:
        memory: 1Gi
        cpu: 1
      requests:
        memory: 1Gi
        cpu: 1
    volumeMounts:
    - mountPath: /data
      name: data-gp-engine-unoselab01
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 0
  volumes:
  - name: data-gp-engine-unoselab01
    persistentVolumeClaim:
      claimName: pvc-gp-engine-unoselab01
