apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shradha-llmast-gp-engine-unoselab01
spec:
  storageClassName: rook-cephfs-central
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi