apiVersion: v1
kind: Pod
metadata:
  name: shradha-llmast-gp-engine-unoselab01-pod
spec:
  automountServiceAccountToken: false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-central 
  containers:
  - name: pod-name-sso
    image: ubuntu:20.04
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
    resources:
      limits:
        memory: 12Gi
        cpu: 2
      requests:
        memory: 10Gi
        cpu: 2
    volumeMounts:
    - mountPath: /data
      name: data-shradha-llmast-gp-engine-unoselab01
  volumes:
    - name: data-shradha-llmast-gp-engine-unoselab01
      persistentVolumeClaim:
        claimName: pvc-shradha-llmast-gp-engine-unoselab01