apiVersion: v1
kind: Pod
metadata:
  name: {{pod_name}}
spec:
  automountServiceAccountToken: false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-central 
  containers:
  - name: causal-model-gp-engine-unoselab01-pod1
    image: ubuntu:20.04
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
    resources:
      limits:
        memory: 25Gi
        cpu: 2
      requests:
        memory: 22Gi
        cpu: 2
    volumeMounts:
    - mountPath: /data
      name: {{persistentVolume_name}}
  volumes:
  - name: {{persistentVolume_name}}
    persistentVolumeClaim:
      claimName: {{persistentVolume_name}}
